### PR TITLE
MSSQL2BVD Connector

### PR DESCRIPTION
**Pull request by unitedart**
This connector helps you to pull SQL Query output and send it to BVD

### CODE REVIEW

**Comment by hulmgulm-at-work** [comment]
Hello,

thank you for your contribution. I had a look at it and am missing a readme on how to use it. I also noticed, that some of the configuration are in a config file and some are in the actual script. It would be great if you could change that.

Thank you,
   Andreas

**Comment by unitedart** [comment]
Thanks for the reply, I have pretty much added the comments inside the code itself. And its almost similar in running like other connectors. And i already referred those to create this. If i get some i will surely add a read me file. I am new to github (or am using after so long time).

**Comment by unitedart** [comment]
I have added read me for the help. Please check.

**Comment by klausb** [comment]
Hi,

thanks for the updates. However could you please consolidate all config settings into the config file? Thanks!

Regards,
klaus

**Comment by unitedart** [comment]
I have consolidated the config settings inside the file.

**Review by unitedart — COMMENTED** [review]
Consolidated all settings into config file.

**Comment by lesteryin** [comment]
I cannot see this MSSQL2BVD Connector under MicroFocus/ColorYourData/connector folder.

**Comment by unitedart** [comment]
I don't have access to upload it directly here, So i uploaded to my clone https://github.com/unitedart/ColorYourData and i did this pull request. please correct me if i am wrong.

**Comment by hulmgulm-at-work** [comment]
This looks great now. Thank you for your contribution.

**Pull request merged**
