### PR TITLE
Create obmConfig.json

### PR DESCRIPTION
**Pull request by kanthi275**
- creating separate PR for config changes.

### CODE REVIEW

**Comment by kanthi275** [comment]
Hi Klaus,
could you please review the changes for data generator for sample OBM Dashboard.

Thanks,
Kanthi.

**Review by klausb — CHANGES_REQUESTED** [review]
The config looks good.
Please add additional info in the README.md to explain the obm config file as one being referenced for the shipped BVD sample dashboard.

**Comment by kanthi275** [comment]
Thank you klaus.
okay I will make the changes to README.md.

**Comment by kanthi275** [comment]
Hi Klaus,

I have updated the README.md file and merging the Pull Request to avoid blocker for testing the feature.

Thanks, 
Kanthi.

**Pull request merged**
